name: fe-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: fe-dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: env 파일 생성
        run: |
          cd ~/code-sync-fe/
          rm .env
          touch .env
          echo VITE_BASE_URL=${{ secrets.VITE_BASE_URL }} >> .env
          echo VITE_WS_URL=${{ secrets.VITE_WS_URL }} >> .env
          echo VITE_PR_URL=${{ secrets.VITE_PR_URL }} >> .env
          echo VITE_YJS_URL=${{ secrets.VITE_YJS_URL }} >> .env
          echo VITE_RTC_ICE=${{ secrets.VITE_RTC_ICE }} >> .env
          echo VITE_ICE_USER=${{ secrets.VITE_ICE_USER }} >> .env
          echo VITE_ICE_PASS=${{ secrets.VITE_ICE_PASS }} >> .env
          cat .env

      - name: run deploy
        run: |
          /bin/bash ~/deploy-fe.sh
